### PR TITLE
Adding print_side to Print Dialogue

### PR DESCRIPTION
**Pull request by RabidCicada**
Attempting to address issue https://github.com/ronplanken/game-datacards/issues/85.

After discussion with @ronplanken on discord it sounds like there is a desire to keep backward compatibilty with previous behavior to help those who already duplicated their cards.

I'll need to add a force override option toggle to the print settings menu.

### CODE REVIEW

**Comment by ronplanken** [comment]
First implementation looks good, but I think we should go another way for the force side printing. The general idea would be:

If a DataCard has no printside defined, then it should follow the selected option in the print settings without having to select Force Side.

If a DataCard has a printside (either front or back) it should always show that side on the printing preview regardless of what option was selected on the "Print Side" setting for printing. With on exception, if a user has selected Force Side, then it should overwrite the selected side from the DataCard itself. 

Also, if a category has no 10th edition cards, the option should hide itself.

We might want to add a tooltip with icon to the title of the options to explain the overwrite options.

 
image

**Comment by ronplanken** [comment]
That is actually a good point. I never implemented sides for the other cards. But it does sound like something that would be useful. Even it if is only a art side (Like Magic the Gathering or so).

How about we leave the button visible for everything and just change the way the overwrite works as I wrote above?

**Comment by RabidCicada** [comment]
Alright sir.  I think I've addressed the suggestions

**Review by ronplanken — APPROVED** [review]
lgtm

**Pull request merged**
